### ISSUE TITLE
Publish 0.4.2 to npm

### ISSUE THREAD

**Issue by drewbo** [JeffDownie/camda#4]
Comparing files, it doesn't look like the version tagged 0.4.2 here is the same as what's installed from npm. Can you republish? Thanks

**Comment by drewbo** [comment]
I tried both `yarn add` and `npm install` and it seems to be missing some files:
```
MD5 (node_modules/camda/LICENSE.txt) = 74091913f272aea40e6535f215f9a895
MD5 (node_modules/camda/README.md) = 47164999a1c75ab089d16814f98d254a
MD5 (node_modules/camda/package.json) = 8be82d84156dc3cda80e25bf97507472
MD5 (node_modules/camda/src/CB/index.js) = 8b652cf19189b426aaa6bc40ae3601c2
MD5 (node_modules/camda/src/index.js) = a8b2947d956c2d833d522244ec1e5d18
MD5 (node_modules/camda/src/utils.js) = b3727c87dfc068bd9363c4f7667170d6
MD5 (node_modules/camda/test/CB/index.js) = b0ce2c9f3d60ebe1f1ba9cefda711962
MD5 (node_modules/camda/test/index.js) = 323315c7a2f37e0527d7d12c4b3c106f
MD5 (node_modules/camda/test/ramdaIntegration/index.js) = 7536866779f5ca3f482420d0b804cade
MD5 (node_modules/camda/test/utils.js) = 6639b99bbe31c7256680be652ecbddee
```

**Comment by drewbo** [comment]
Actually this matches what I get from a github clone as well, seems like OSX doesn't differentiate between upper/lowercase (so it doesn't get both CB and cb)

**Comment by JeffDownie** [comment]
Ah! I'll bet you're running on a Windows machine - if I remember correctly, Windows doesn't do case-sensitivity properly.

I suspect just renaming the folders will fix it

**Comment by drewbo** [comment]
I'm on OSX but maybe somewhere in the pipeline it gets swapped up. Thanks for the quick feedback

**Comment by JeffDownie** [comment]
Should be all good now - I've settled on names of `callee` & `caller` as the longer variants of `cb` & `CB` respectively.

Could you try v0.4.4 to check? (I had to skip a patch version)
